version: '3'
services:
  api: 
    build: 
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "8000:4000"
    environment:
      - PORT=8000