version: '3.5'
services:
  api: 
    build: 
      context: backend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
  client:
    build: 
      context: fontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./fontend:/app
    ports:
      - "8001:8001"